# Generated by Django 4.2.11 on 2024-04-11 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retriever', '0002_documents_delete_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='documents',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='documents',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
    ]
